### ISSUE TITLE
TODO Back 6

### ISSUE THREAD

**Issue by marcinlacina** [marcinlacina/Mirror#6]
- [x] Entity is not instance of Attachment (Exception)
- [x] Find user vote value.
- [x] $fiPosts is $posts
- [x] Find one Attachment by filename.
- [x] KERNEL_DIR (./app)
- [ ] UserController Test
- [ ] TNaviTest pageNotFound
